# for reproducibility
seed: 0
# path to save logs and models
default_root_dir: 'experiments/editor_snli_sparsemap_50p/'


# training args
train:
    # path to the pre-trained masker checkpoint
    factual_ckpt: experiments/masker_snli_sparsemap_50p/versionjkexuek0/checkpoints/epoch=1.ckpt
    load_tokenizer: False       # load a trained tokenizer stored in the checkpoint dir as `tokenizer.pickle`
    load_label_encoder: False   # load a trained label encoder stored in the checkpoint dir as `label_encoder.pickle`
    save_edits: False           # will be saved in a .txt in the default_root_dir as `{test|val}_edits.txt`

    # wandb for logging (optional, comment to disable)
    wandb_project: 'cfrat'
    wandb_entity: 'mtreviso'

    # io
    save_rationales: False      # will be saved in a .txt in the default_root_dir as `{test|val}_rationales.txt`
    save_counterfactuals: False # will be saved in a .txt in the default_root_dir as `{test|val}_counterfactuals.txt`
    save_tokenizer: False       # the tokenizer will be pickled and store in the checkpoint dir as `tokenizer.pickle`
    save_label_encoder: False   # the label encoder will be pickled and store in the checkpoint dir as `label_encoder.pickle`
    gpu_log: False              # whether to use the gpu callback to see gpu information in the logger

    # data
    dm: 'snli'                  # data module name (see docs for more options)
    batch_size: 32              # minibatch size
    num_workers: 1              # number of workers used for data loading (0 means that only a single core will be used)
    vocab_min_occurrences:  1   # frequency for a token to be added to the vocabulary
    max_seq_len: 512            # pretrained transformer limitation
    # max_dataset_size: 64      # limit dataset size (useful for quick testing)
    ignore_neutrals: True       # whether to ignore neutral examples in the dataset

    # early stopping
    monitor: 'val_sum_loss'     # quantity to be monitored
    monitor_mode: 'min'         # whether to see if monitored metric has stopped decreasing (min) or increasing (max)
    monitor_patience: 5         # number of epochs to wait for early stopping

    # pytorch-lightning rationalizer model
    model: 'editor'

    # load a checkpoint
    # ckpt: null  # path to the checkpoint to be loaded

    # factual flow
    tokenizer: 't5-small'               # Pre-trained tokenizer from the Hugging Face hub. If None, a nltk's WordPunct tokenizer is used
    gen_arch: 't5-small'                # Pre-trained generator from the Hugging Face hub
    pred_arch: 't5-small'               # Pre-trained predictor from the Hugging Face hub
    gen_emb_requires_grad: False        # whether to fine-tune the generator's embedding layer
    gen_encoder_requires_grad: False    # whether to fine-tune the generator's encoder
    pred_emb_requires_grad: False       # whether to fine-tune the predictor's embedding layer
    pred_encoder_requires_grad: False   # whether to fine-tune the predictor's encoder
    pred_output_requires_grad: False    # whether to fine-tune the predictor's output layer
    explainer_requires_grad: False      # whether to fine-tune the explainer (including the mlp)

    # editor
    cf_gen_arch: "t5-small"                 # pre-trained generator from the Hugging Face hub
    cf_prepend_label_type: "gold"           # whether to prepend gold (`gold`) or predicted (`pred`) labels to the input of the editor
    cf_z_type: "pred"                       # whether to use the masker's explanations (`pred`) or gold explanations, when available (`gold`)
    cf_task_name: "binary_classification"   # the name of the task at hand, used to create the name of prepend labels: `binary_classification`, `nli`, `nli_no_neutrals`
    cf_classify_edits: True                 # whether to classify the edits after generation

    # https://huggingface.co/docs/transformers/v4.23.1/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate
    cf_generate_kwargs:
        do_sample: False            # deterministic or stochastic generation
        num_beams: 15               # mice: 15
        num_beam_groups: 1          # to promote diversity in beam groups
        early_stopping: True        # stop search when >= num_beams sentences are done (default: False | mice: True)
        length_penalty: 1.0         # (<1) means shorter sequences, (>1) longer sequences
        top_k: 30                   # default: 50  | mice: 30
        top_p: 0.95                 # default: 1.0 | mice: 0.95
        typical_p: null             # default: 1.0
        no_repeat_ngram_size: 2     # no bigrams repetitions are allowed (default: 0 | mice: 2)
        num_return_sequences: 1     # sample N sequences
        min_length: null            # minimum length of the generated sequence
        max_length: 512             # maximum length of the generated sequence (default: 512 | mice: 512)

    # model: optimizer
    optimizer: 'adamw'
    lr: 0.0001
    weight_decay: 0.000001
    betas: [0.9, 0.999]
    amsgrad: False
    momentum: 0.0
    dampening: 0.0
    nesterov: False
    alpha: 0.99   # for rmsprop
    centered: False  # for rmsprop
    lambd: 0.0001  # for asgd
    t0: 1000000.0  # for asgd

    # model: lr scheduler
    #scheduler: 'multistep'
    #milestones: [25, 50, 75]
    #lr_decay: 0.97  # a.k.a gamma

    # trainer (will be passed to pytorch-lightning's Trainer object)
    # see the complete list here: https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-flags
    accelerator: gpu
    devices: 1
    gradient_clip_val: 5.0
    min_epochs: 3
    max_epochs: 20
    #limit_train_batches: 10
    #limit_val_batches: 1
    #limit_test_batches: 1
    #log_every_n_steps: 25


# the options defined here will overwrite the ones defined in the checkpoint
predict:
    # ckpt: null               # will be defined via cli --ckpt or will get last checkpoint version if it exists
    accelerator: gpu
    devices: 1
    load_tokenizer: False       # load a trained tokenizer stored in the checkpoint dir as `tokenizer.pickle`
    load_label_encoder: False   # load a trained label encoder stored in the checkpoint dir as `label_encoder.pickle`
    save_rationales: True       # will be saved in a .txt in the default_root_dir as `{test|val}_rationales.txt`
    save_edits: True            # will be saved in a .txt in the default_root_dir as `{test|val}_edits.txt`
    cf_classify_edits: True
